### ISSUE TITLE
Request black

### ISSUE THREAD

**Issue by atugushev** [LambdaLint/lambdalint.github.io#1]
Would be nice to have `black` checker.

**Comment by atugushev** [comment]
Oh, i see there is a repo for black already in the org. Hope to see it working soon.

**Comment by codingjoe** [comment]
Hi @atugushev 
yes, that would be great. Sadly `black` so opinionated, that they only support systems with multiprocessing support. On AWS, you can't create new child processes.

Feel free to reach out to the black team and let them know that you want FussyFox support.

Seealso https://github.com/FussyFox/black/issues/5

Best Joe
