### ISSUE TITLE
Rename too generic .checks.yml

### ISSUE THREAD

**Issue by atugushev** [LambdaLint/lambdalint.github.io#2]
Rename `.checks.yml` to something related to FussyFox brand (ie: `.fussyfox.yml`), for it is too generic name.

**Comment by codingjoe** [comment]
Hi @atugushev,

thanks for reaching out. I see you point, but I renamed the projects multiple times already. I don't know of anyone using the name `.checks.py`, so we should be good for now. I am considering adding support for multiple names in the future. I simply haven't gotten around to it yet.
Feel free suggest a change over here: https://github.com/FussyFox/suite/blob/964d8ddc73ec8936afa22f98dd0e6e853dcdea9b/suite.py#L24

Best
-joe

**Comment by codingjoe** [comment]
Ok, I just implemented it. You can use `.fussyfox.yml` now as well as other names.

**Comment by atugushev** [comment]
Awesome!

**Comment by jezdez** [comment]
See #3 for an update of the README.
