### ISSUE TITLE
Bandit check has stucked

### ISSUE THREAD

**Issue by atugushev** [LambdaLint/lambdalint.github.io#4]
Could you check what's wrong?

https://github.com/jazzband/pip-tools/runs/126356308

**Comment by codingjoe** [comment]
Hi @atugushev,

yes you are right, there is a problem with the latest bandit version, see https://github.com/PyCQA/bandit/issues/490

I will downgrade for now and hope my patch will be released soon.

Best
-Joe

**Comment by atugushev** [comment]
`Bandit` has stucked again https://github.com/jazzband/pip-tools/runs/162425348 :(

**Comment by codingjoe** [comment]
Thanks @atugushev for reporting this. It's another problem tho. Your config seems to be off.
Can you run bandit locally?

The body is too large to be patched to GitHub, their API returns:
```
422 Client Error: Unprocessable Entity
```

**Comment by codingjoe** [comment]
@atugushev this patch should solve the issue:
https://github.com/FussyFox/lintipy/releases/tag/1.2.2

**Comment by atugushev** [comment]
Awesome! Thanks @codingjoe!

**Comment by atugushev** [comment]
I've checked and it seems the problem has not been resolved, because the last checker still in progress. See https://github.com/jazzband/pip-tools/runs/163018997

UPDATE: my fault, everything is OK

**Comment by codingjoe** [comment]
@atugushev there also continues to be a problem with the latest bandit version. We will skip further releases until all problems are dealt with.
